spring.application.name=security

# Base de datos (referenciando variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de seguridad
security.jwt.private.key = ${PRIVATE_KEY}
security.jwt.user.generator=${USER_GENERATOR}
security.jwt.expiration.time=${EXPIRATION_TIME}

google.client.id = ${GOOGLE_ID}

# Configuración del servidor SMTP de Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=labortrack69@gmail.com
spring.mail.password=gqyuyvdnwkmzsqug

# Propiedades de seguridad
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true